### ISSUE TITLE
seed targetness label 

### ISSUE THREAD

**Issue by gongshichina** [HaozheQi/P2B#1]
https://github.com/HaozheQi/P2B/blob/9015b9161db594d4650bfacb8aea49c36b7befc9/kitty_utils.py#L125

Hello, thanks for your good job. I have a question about this line in your code:

Why we can just take the first 128 numbers in the target mask as seed targetness label?

**Comment by HaozheQi** [comment]
Hi, @gongshichina ,

Thanks for your attention to our work.Given an input point cloud from search area, we normalize the component points into 1024 ones with random abandoning or duplicating. The result points are fed into three-layer PointNet++ with 8 times down-sampling and yielding 128 seeds. The downsampling is actually a random process. Since the input points have been randomized, here we sample the first 128 points as final seeds. This explains the number selection in your question.
