### ISSUE TITLE
point cloud and boxes visualization

### ISSUE THREAD

**Issue by WangZhouTao** [HaozheQi/P2B#10]
Hi, thank you for your good work.
I try to visualize the model output of PCB.
I employ mayavi to visualize candidate_PCs and BBs[I] in test_tracking.py[https://github.com/HaozheQi/P2B/blob/ccac70ffad40a1f9b21c617223bfd0c04e2d4359/test_tracking.py](url).
But there were some problems with the results, the box didn't align with the point cloud.
Is there any transformation involved?
![image](https://user-images.githubusercontent.com/9363268/85018426-c1596880-b19f-11ea-9ffd-68f7e0f533fc.png)
I look forward to your reply.

**Comment by HaozheQi** [comment]
Hi, @WangZhouTao .

I think you got this problem because the points were normalized while the box was the initial one. When you normalize the point cloud, the box should be changed accrodingly. The code [there](https://github.com/HaozheQi/P2B/blob/master/kitty_utils.py#L346) may give you a reference.

Hope this can sovle your problem.

**Comment by WangZhouTao** [comment]
Thank you for your advice. I have solved the problem.
